<<<<<<< HEAD
import type { Metadata } from "next";
import "./globals.css";
import RecoilRootProvider from "@/utils/RecoilRootProvider";

export const metadata: Metadata = {
  title: "APtrue",
  description: "아파트의 진실을 알고 싶다면, 아파트루(APTrue.)!",
=======
import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> 040e5e6e1ae71089ea380034a80aa3ffda727d82
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RecoilRootProvider>{children}</RecoilRootProvider>
      </body>
    </html>
  );
}
